---
- name: Kubeconfig download block
  block:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Create the local kubeconfig directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube/kubeconfigs"
        state: directory
        mode: "0755"
      register: kubeconfig_dir

    - name: Grab the workload cluster kubeconfig from the default directory
      ansible.builtin.copy:
        src: "{{ kubeconfig_location }}/"
        dest: "{{ kubeconfig_dir.path }}/{{ cluster_name }}.kubeconfig"
        mode: '0644'

    - name: Create a list of all local kubeconfig files
      ansible.builtin.find:
        path: "{{ kubeconfig_dir.path }}"
        patterns: "*.kubeconfig"
      register: kubeconfig_list

    - name: Merge the local kubeconfig file
      ansible.builtin.shell: kubectl config view --merge --flatten > "{{ ansible_env.HOME }}/.kube/config"
      environment:
        KUBECONFIG: "{{ kubeconfig_list | json_query('files[].path') | join(':') }}"