---
- name: Check whether the management cluster already exists
  ansible.builtin.wait_for:
    port: 6443
    timeout: 5
    host: "{{ vsphere_control_plane_endpoint }}"
    state: started
  ignore_errors: true
  register: mgmt_cluster_is_present

- name: Include mgmt cluster creation task
  ansible.builtin.import_tasks: mgmt_cluster_create.yml
  tags: ["tkg", "tkg_mgmt"]
  when: 
    - mgmt_cluster_is_present is failed
    - delete_cluster is false
  delegate_to: localhost

- name: Include mgmt cluster deletion task
  ansible.builtin.import_tasks: mgmt_cluster_delete.yml
  tags: ["tkg", "tkg_mgmt"]
  when: 
    - mgmt_cluster_is_present is succeeded
    - delete_cluster is true
  delegate_to: localhost